COPY USR FROM '/home/csmajs/irake001/CS166_Project/data/USR-Table.csv'
DELIMITER ',' CSV HEADER;
COPY EDUCATIONAL_DETAILS FROM '/home/csmajs/irake001/CS166_Project/data/Edu_Det-Table.csv'
DELIMITER ',' CSV HEADER;
COPY WORK_EXPR FROM '/home/csmajs/irake001/CS166_Project/data/Work_Ex-Table.csv'
DELIMITER ',' CSV HEADER;
COPY CONNECTION_USR FROM '/home/csmajs/irake001/CS166_Project/data/Connection-Table.csv'
DELIMITER ',' CSV HEADER;
COPY MESSAGE FROM '/home/csmajs/irake001/CS166_Project/data/Message-Table.tsv'
DELIMITER E'\t' CSV HEADER;
